### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by zfha** [zixia/node-facenet#154]
```
node-pre-gyp ERR! Tried to download(404): https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.0.0-alpha.14/canvas-prebuilt-v2.0.0-alpha.14-node-v64-darwin-unknown-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for canvas@2.0.0-alpha.14 and node@10.6.0 (node-v64 ABI, unknown) (falling back to source compilewith node-gyp)
/bin/sh: pkg-config: command not found
gyp: Call to 'pkg-config pixman-1 --libs' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build""--module=/Users/zhoufan/Documents/bmatch/wechaty/node_modules/canvas/build/Release/canvas-prebuilt.node" "--module_name=canvas-prebuilt" "--module_path=/Users/zhoufan/Documents/bmatch/wechaty/node_modules/canvas/build/Release" "--napi_version=3" "--node_abi_napi=napi"
gyp ERR! cwd /Users/zhoufan/Documents/bmatch/wechaty/node_modules/canvas
gyp ERR! node -v v10.6.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/zhoufan/Documents/bmatch/wechaty/node_modules/canvas/build/Release/canvas-prebuilt.node --module_name=canvas-prebuilt --module_path=/Users/zhoufan/Documents/bmatch/wechaty/node_modules/canvas/build/Release --napi_version=3 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/zhoufan/Documents/bmatch/wechaty/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:961:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
node-pre-gyp ERR! System Darwin 17.7.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/zhoufan/Documents/bmatch/wechaty/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/zhoufan/Documents/bmatch/wechaty/node_modules/canvas
node-pre-gyp ERR! node -v v10.6.0
node-pre-gyp ERR! node-pre-gyp -v v0.9.1
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/zhoufan/Documents/bmatch/wechaty/node_modules/canvas/build/Release/canvas-prebuilt.node --module_name=canvas-prebuilt --module_path=/Users/zhoufan/Documents/bmatch/wechaty/node_modules/canvas/build/Release --napi_version=3 --node_abi_napi=napi' (1)
npm WARN facenet@0.10.3 requires a peer of flash-store@^0.1.2 but none is installed. You must install peer dependencies yourself.
npm WARN facenet@0.10.3 requires a peer of numjs@^0.14 but none is installed. You must install peer dependencies yourself.
npm WARN wechaty@1.0.0 No description
npm WARN wechaty@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvas@2.0.0-alpha.14 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the canvas@2.0.0-alpha.14 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/zhoufan/.npm/_logs/2018-09-18T09_04_01_767Z-debug.log
```

**Comment by zfha** [comment]
why this resource is not found?
```
Tried to download(404): https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.0.0-alpha.14/canvas-prebuilt-v2.0.0-alpha.14-node-v64-darwin-unknown-x64.tar.gz
```

**Comment by joni-mikkola** [comment]
There is indeed some problem with this resource missing, however it seems you can compile from the source in that case.
You need to download all dependencies, starting from pkg-config "/bin/sh: pkg-config: command not found".
