### ISSUE TITLE
TypeError when running the codes

### ISSUE THREAD

**Issue by henrych4** [zixia/node-facenet#68]
I tried to run the library with nodejs and error occured.

Symbol.asyncIterator = Symbol.asyncIterator || Symbol.for('Symbol.asyncIterator');
                         ^
TypeError: Cannot assign to read only property 'asyncIterator' of function 'function Symbol() { [native code] }'
    at /Users/hhhung/Desktop/face_feature/node_modules/flash-store/bundles/flash-store.umd.js:101:26
    at rimrafProxy__default (/Users/hhhung/Desktop/face_feature/node_modules/flash-store/bundles/flash-store.umd.js:40:68)
    at Object.<anonymous> (/Users/hhhung/Desktop/face_feature/node_modules/flash-store/bundles/flash-store.umd.js:43:2)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)

flash-store version: 0.1.2
How could I fix the problem? Thanks

**Comment by zixia** [comment]
Which node version did you use?
Did you tired node v8? I believe it would work with problem under the latest version of node.

**Comment by henrych4** [comment]
I used node v8 at first and I changed to v7.0.0 but same error appears.

**Comment by zixia** [comment]
Could you please post your code which can reproduce this issue?

**Comment by henrych4** [comment]
import 'babel-polyfill'                                                                                                           
import { tmp } from './module'

tmp()

----------------------------------------------------------------------------------------------------

import { Facenet } from 'facenet'                                                                                                 

export async function tmp(){
    const facenet = new Facenet()
    const imageFile = `./test.png`
    const faceList = await facenet.align(imageFile)

    for (const face of faceList) {
        const embedding = await facenet.embedding(face)
        console.log('embedding: ', embedding)
    }   
}

Then I use babel to convert the two codes into es5.

**Comment by zixia** [comment]
Thank you for providing the re-produce code.

Could try to run them by `babel-node` and see if it will produce the same result?

**Comment by henrych4** [comment]
Errors occur when running by babel-node

For index.js(upper one):
throw new Error("only one instance of babel-polyfill is allowed");
  ^
Error: only one instance of babel-polyfill is allowed


For test.js(lower one):
throw err;
      ^
SyntaxError: /Users/hhhung/Desktop/face_feature/test.js: await is a reserved word (6:17)

**Comment by zixia** [comment]
Could you be able to run the demo from this repository?

It uses ts-node and should work without any problem.

Try run `npm run demo`

I have never tried babel, will try it when I have time.

**Comment by henrych4** [comment]
Thanks for your advices. Now I am able to run the codes and  I have one more question. Is there any requirement for the input photo? I use some face photos as input but no face feature vector is returned.

**Comment by zixia** [comment]
There's two steps: alignment and embedding.

Which one did you tried, alignment or embedding?

I suggest you to read the source code to get to know the reason.

If you still has problem, please provide the reproduce procedure for your issue.

**Comment by henrych4** [comment]
Just tried embedding function with size 256x256, 128x128 and 96x96 face photos. Only the one with size 256x256 returns a feature vector.

**Comment by zixia** [comment]
Actually, I believe all the input image will be resized to 160x160 before feed to the neural network.

So the `facenet.embedding()` should return the 128 dim vector no matter than what size the image is.

You can check the source code, and let me know your result.

Thanks.

**Comment by henrych4** [comment]
I ran the demo with replacing the input,
const imageFile = `${__dirname}/../tests/fixtures/two-faces.jpg`
with a 96x96 jpg.
No result is returned.
But when the photo is enlarged to higher dimension, like 256x256, an embedding vector is returned.
